import { test } from '@playwright/test';

test('Plan Dropdown Debug', async ({ page }) => {
    
  await page.goto('https://slicuatc.shriramlife.in/statimliidp/Account/Login?ReturnUrl=%2Fstatimliidp%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dastra_web_client%26redirect_uri%3Dhttps%253A%252F%252Fslicuatc.shriramlife.in%252FSTATIMLIASTRA%252Fcallback%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520api1%26state%3D8d7c34beff20415ba161a699130d53f4%26code_challenge%3Dl6TdJTL1fSyvFc6VZ8ZheosWCHKeKgF5KXja5phWYDU%26code_challenge_method%3DS256%26response_mode%3Dquery');
  await page.getByRole('textbox', { name: 'User ID' }).click();
  await page.getByRole('textbox', { name: 'User ID' }).fill('B50088');
  await page.getByRole('textbox', { name: 'User ID' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Welcome@123');
  await page.locator('#txtbxCaptcha').click();
  await page.locator('#txtbxCaptcha').fill('1234');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('img', { name: 'Proposal Icon' }).first().click();
  await page.locator('span').nth(5).click();
  await page.getByText('B03063-4189-YERRAGUNDLA OL AP').click();
  await page.getByText('Own Life').click();
  await page.getByText('Own Life').nth(1).click();
  await page.getByText('New Customer').click();
  await page.getByText('New Customer').nth(1).click();
  await page.locator('.ant-row.mb-3 > div > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').first().click();
  await page.getByText('Mr.').click();
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('TESt');
  await page.getByRole('textbox', { name: 'First Name*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Middle Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name*' }).click();
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('PURPOSe');
  await page.getByRole('textbox', { name: 'LA Aadhar No (Enter Last 4' }).click();
  await page.getByRole('textbox', { name: 'LA Aadhar No (Enter Last 4' }).fill('4567');
  await page.locator('div:nth-child(4) > div > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').first().click();
  await page.getByTitle('SHRIRAM LIFE GOLDEN JUBILEE PLAN V0X').click();
  await page.locator('div:nth-child(3) > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByText('Yearly', { exact: true }).click();
  await page.locator('.ant-row.mb-3 > div:nth-child(5) > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByText('Collected', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Agent Code' }).click();
  await page.getByRole('textbox', { name: 'Agent Code' }).fill('M04139');
  await page.locator('.anticon.anticon-search > svg').first().click();
  await page.getByRole('textbox', { name: 'Agent Name*' }).click();
  await page.getByText('BHi BRAHMANANDA REDDY S').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Address 1*' }).click();
  await page.getByRole('textbox', { name: 'Address 1*' }).fill('36');
  await page.getByRole('textbox', { name: 'Address 1*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Address 2' }).click();
  await page.getByRole('textbox', { name: 'Address 2' }).click();
  await page.getByRole('textbox', { name: 'Address 2' }).fill('hgdjh');
  await page.getByRole('textbox', { name: 'Address 2' }).press('Tab');
  await page.getByRole('textbox', { name: 'Pincode*' }).click();
  await page.getByRole('textbox', { name: 'Pincode*' }).fill('500044');
  await page.locator('.ant-row.mb-3 > div:nth-child(7) > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByText('Andhra Mahila Sabha').click();
  await page.getByText('Andhra Mahila Sabha').click();
  await page.getByRole('textbox', { name: 'Phone' }).click();
  await page.getByRole('textbox', { name: 'Phone' }).fill('8656576477');
  await page.getByRole('textbox', { name: 'Mobile*' }).click();
  await page.getByRole('textbox', { name: 'Mobile*' }).fill('7564767676');
  await page.getByRole('button', { name: 'Rural' }).click();
  await page.getByRole('button', { name: 'No' }).nth(1).click();
  await page.getByText('YesNo').first().click();
  await page.getByRole('button', { name: 'No' }).first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('.ant-row.mb-3 > .ant-col > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByText('PAN').click();
  await page.getByRole('textbox', { name: 'LA PAN No*' }).click();
  await page.getByRole('textbox', { name: 'LA PAN No*' }).fill('DFGRT4567y');
  await page.getByRole('textbox', { name: 'Proposer PAN No' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Receipt Amount*' }).click();
  await page.getByRole('textbox', { name: 'Receipt Amount*' }).fill('100000');
  await page.locator('div:nth-child(3) > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByTitle('Cheque').click();
  await page.getByRole('textbox', { name: 'Instrument Amount*' }).click();
  await page.getByRole('textbox', { name: 'Instrument Amount*' }).fill('100000');
  await page.locator('.ant-row.mb-3 > div:nth-child(5) > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByTitle('HDFC CMS A/C XXX1323 - SEC DO').click();
  await page.getByRole('textbox', { name: 'Instrument No*' }).click();
  await page.getByRole('textbox', { name: 'Instrument No*' }).fill('764676');
  await page.locator('input[name="NPDRInstrumentDatePaidByCheque"]').click();
  await page.getByText('2').nth(4).click();
  await page.locator('div:nth-child(8) > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByTitle('A P MAHESH CO URBAN BANK').click();
  await page.locator('div:nth-child(9) > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByText('CTS').click();
  await page.locator('div:nth-child(10) > .main_dropdown > .float-label > .Common-dropdown > .ant-select > .ant-select-selector > .ant-select-selection-item').click();
  await page.getByText('Local').click();
  await page.getByRole('textbox', { name: 'Payable At*' }).click();
  await page.getByRole('textbox', { name: 'Payable At*' }).fill('KOTi');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Proposal/Policy No').click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('img', { name: 'Download Receipt' }).click();
  const download = await downloadPromise;
});


});